'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {useDashboardTool} from './webmcp';
import {ArrowUpRight,ArrowDownRight,ArrowRight,Users,Ticket,TrendingUp,Sparkles,Search,RefreshCw,CalendarDays,Flame,CircleHelp} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Skeleton} from '@/components/ui/skeleton';
import {Shell} from './shell';
import {ForecastChart} from './chart';
import {DEMO_DATE,mockBoxOffice} from '@/lib/cinema/mock';
import {compact,forecast} from '@/lib/cinema/forecast';
import type {BoxOffice,Horizon,Metric,Period} from '@/lib/cinema/types';
export function Change({value}:{value:number}){return <span className={value>=0?'positive':'negative'}>{value>=0?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {Math.abs(value).toFixed(1)}%</span>}
export function Dashboard(){
 const [period,setPeriod]=useState<Period>('daily'),[date,setDate]=useState(DEMO_DATE),[source,setSource]=useState('mock');
 const [data,setData]=useState<BoxOffice>(()=>mockBoxOffice()),[loading,setLoading]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const [search,setSearch]=useState(''),[genre,setGenre]=useState('all'),[metric,setMetric]=useState<Metric>('audience'),[horizon,setHorizon]=useState<Horizon>(7);
 const toolGenres=useMemo(()=>[...new Set(data.movies.map(m=>m.genre))],[data]);
 useDashboardTool(toolGenres,useCallback(v=>{setSearch(v.search);setGenre(v.genre);setHorizon(v.horizon)},[]));
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch(`/api/boxoffice?period=${period}&date=${date}&source=${source}&history=true`,{signal:controller.signal}).then(async r=>{const d=await r.json() as BoxOffice & {error?:string};if(!r.ok)throw new Error(d.error||'데이터를 불러오지 못했습니다.');return d}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[period,date,source,revision]);
 useEffect(()=>{const t=setInterval(()=>setRevision(n=>n+1),300000);return()=>clearInterval(t)},[]);
 const filtered=data.movies.filter(m=>m.title.toLowerCase().includes(search.toLowerCase())&&(genre==='all'||m.genre===genre));
 const total=data.movies.reduce((s,m)=>s+m.audience,0),revenue=data.movies.reduce((s,m)=>s+m.revenue,0),previous=data.movies.reduce((s,m)=>s+m.audience/(1+m.audienceChange/100),0);
 const selected=data.movies[0],prediction=useMemo(()=>selected?forecast(selected,horizon,metric):null,[selected,horizon,metric]);
 const rising=[...data.movies].filter(m=>m.audienceChange>0).sort((a,b)=>b.audienceChange-a.audienceChange).slice(0,3);
 const detail=(id:string)=>`/movies/${id}?source=${data.source}&date=${data.date}`;
 return <Shell><main className="dashboard page-enter"><div className="page-heading"><div><div className="eyebrow">THE BIG PICTURE</div><h1>흥행의 흐름, 그다음까지<span>.</span></h1><p>오늘의 박스오피스와 내일의 가능성을 한눈에 확인하세요.</p></div><Button variant="outline" className="refresh-button" disabled={loading} onClick={()=>setRevision(n=>n+1)}><RefreshCw className={loading?'spin':''} size={15}/>새로고침</Button></div>
 <div className="toolbar"><div className="toolbar-left"><Tabs value={period} onValueChange={v=>setPeriod(v as Period)}><TabsList><TabsTrigger value="daily">일간</TabsTrigger><TabsTrigger value="weekly">주간</TabsTrigger></TabsList></Tabs><label className="date-control"><CalendarDays size={15}/><input type="date" aria-label="집계 기준일" value={date} max={source==='mock'?DEMO_DATE:new Date(Date.now()+9*3600000-86400000).toISOString().slice(0,10)} min="2026-01-01" onChange={e=>e.target.value&&setDate(e.target.value)}/></label></div><div className="toolbar-right"><Select value={source} onValueChange={setSource}><SelectTrigger aria-label="데이터 소스"><SelectValue>{source==='mock'?'샘플 데이터':'KOBIS 실적'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="mock">샘플 데이터</SelectItem><SelectItem value="kobis">KOBIS 실적</SelectItem></SelectContent></Select><span className="updated">{data.source==='mock'?'DEMO':'KOBIS'} · 5분 자동 갱신</span></div></div>
 {error&&<div role="alert" className="error-banner">{error} <Button variant="ghost" onClick={()=>{setSource('mock');setRevision(n=>n+1)}}>샘플 데이터로 보기</Button></div>}<div className="data-note"><span className="sample-dot"/>{data.note}</div>
 <div className={error?'stale-content':''} aria-busy={loading}><section className="kpi-grid">{[
 {label:`${data.period==='daily'?'일간':'주간'} 관객수`,value:compact(total),unit:'명',icon:Users,change:previous?(total/previous-1)*100:0,foot:'TOP 10 합계'},
 {label:`${data.period==='daily'?'일간':'주간'} 매출`,value:compact(revenue),unit:'원',icon:Ticket,change:null,foot:'TOP 10 합계'},
 {label:'관객수 1위',value:selected?.title||'집계 대기',unit:'',icon:TrendingUp,change:selected?.audienceChange,foot:selected?`${compact(selected.audience)}명 관람`:''},
 {label:'7일 추가 관객 예측',value:selected&&forecast(selected,7,'audience')?compact(forecast(selected,7,'audience')!.total):'—',unit:'명',icon:Sparkles,change:null,foot:`1위 영화 · 시뮬레이션`}
 ].map((k,i)=><article className={`kpi ${i===3?'kpi-purple':''}`} key={k.label}><div className="kpi-label">{k.label}<k.icon size={17}/></div>{loading?<Skeleton className="h-10 w-32 my-3"/>:<div className={`kpi-value ${i===2?'movie-kpi':''}`}>{k.value}<span>{k.unit}</span></div>}<div className="kpi-foot">{k.change!=null&&<Change value={k.change}/>}<span>{k.foot}</span></div></article>)}</section>
 <section className="insight-grid"><article className="panel forecast-panel"><div className="panel-heading"><div><div className="section-overline"><Sparkles size={14}/> FORECAST INSIGHT</div><h2>실적을 넘어, 다음 장면으로</h2><p>{selected?.title} <span>·</span> 일별 실적과 향후 {horizon}일 예측</p></div><Select value={String(horizon)} onValueChange={v=>setHorizon(Number(v) as Horizon)}><SelectTrigger aria-label="예측 기간"><SelectValue>{horizon}일 예측</SelectValue></SelectTrigger><SelectContent>{[7,14,30].map(n=><SelectItem key={n} value={String(n)}>{n}일 예측</SelectItem>)}</SelectContent></Select></div><div className="chart-toolbar"><Tabs value={metric} onValueChange={v=>setMetric(v as Metric)}><TabsList variant="line"><TabsTrigger value="audience">관객수</TabsTrigger><TabsTrigger value="revenue">매출</TabsTrigger></TabsList></Tabs><div className="chart-legend"><span><i className="actual-dot"/>실적</span><span><i/>예측</span><span className="band-legend"><i/>예측 구간</span></div></div>{prediction?<ForecastChart points={prediction.points} metric={metric} cutoff={selected.history.at(-1)!.date}/>:<div className="empty-state">7일 이상의 일별 실적이 필요합니다.</div>}<div className="chart-bottom"><span><CircleHelp size={13}/> 신뢰구간·예측값은 검증 전 시뮬레이션입니다.</span>{selected&&<Link href={detail(selected.id)}>상세 분석 <ArrowRight size={14}/></Link>}</div></article>
 <aside className="panel spotlight"><div className="section-overline"><Sparkles size={15}/> IN THE SPOTLIGHT</div><span className="spotlight-number">01</span><div className="spotlight-title"><small>{selected?.english}</small><h2>{selected?.title}</h2><p>{selected?.genre} <span>·</span> 박스오피스 1위</p></div><div className="spotlight-stat"><span>향후 7일 추가 관객</span><strong>{selected&&forecast(selected,7,'audience')?compact(forecast(selected,7,'audience')!.total):'—'}<small>명</small></strong></div><div className="spotlight-divider"/><div className="spotlight-row"><span>예매율 {data.source==='mock'?'(샘플)':''}</span><strong>{selected?.reservation!=null?`${selected.reservation}%`:'미제공'}</strong></div><div className="reservation-track"><span style={{width:`${selected?.reservation||0}%`}}/></div><p className="spotlight-note">최근 관객 흐름을 반영한<br/>데모 예측 모델의 분석입니다.</p>{selected&&<Link className="spotlight-link" href={detail(selected.id)}>영화 인사이트 보기 <ArrowUpRight size={17}/></Link>}</aside></section>
 <section id="boxoffice" className="boxoffice-section"><div className="section-heading"><div><h2>박스오피스 <span className="top10">TOP 10</span></h2><p>{data.range.replaceAll('-','.')} 기준 · 전국 영화관</p></div><div className="table-filters"><label className="search"><Search size={16}/><input aria-label="영화 검색" placeholder="영화 검색..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="검색 지우기" onClick={()=>setSearch('')}>×</button>}</label><Select value={genre} onValueChange={setGenre}><SelectTrigger aria-label="장르 필터"><SelectValue>{genre==='all'?'전체 장르':genre}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">전체 장르</SelectItem>{[...new Set(data.movies.map(m=>m.genre))].map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select></div></div><div className="table-wrap"><table><thead><tr><th>순위</th><th>영화</th><th>관객수</th><th>매출</th><th>관객 증감률</th><th>매출 증감률</th><th>예매율{data.source==='mock'?' · 샘플':''}</th><th/></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td className={`rank ${m.rank<=3?'rank-top':''}`}>{String(m.rank).padStart(2,'0')}</td><td><Link className="movie-cell" href={detail(m.id)}><span className="movie-tile" style={{'--movie-color':m.color} as React.CSSProperties}>{m.english.slice(0,1)}</span><span><strong>{m.title}</strong><small>{m.genre} <span>·</span> {m.released.replaceAll('-','.')}</small></span></Link></td><td className="numeric">{m.audience.toLocaleString()}<small>명</small></td><td className="numeric">{compact(m.revenue)}<small>원</small></td><td><Change value={m.audienceChange}/></td><td><Change value={m.revenueChange}/></td><td className="reservation-cell">{m.reservation!=null?<><span>{m.reservation}%</span><div><i style={{width:`${m.reservation*3}%`}}/></div></>:'미제공'}</td><td><Link className="row-link" aria-label={`${m.title} 상세 분석`} href={detail(m.id)}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state"><Search/><h3>검색 결과가 없습니다</h3><p>다른 영화명이나 장르로 찾아보세요.</p><Button variant="outline" onClick={()=>{setSearch('');setGenre('all')}}>필터 초기화</Button></div>}</div></section>
 <section id="rising" className="rising-section"><div className="section-heading"><div><h2><Flame size={20}/> 지금, 빠르게 떠오르는 영화</h2><p>선택한 집계 기간의 관객 증가율 기준</p></div><span className="subtle-label">RISING MOVIES</span></div><div className="rising-grid">{rising.map((m,i)=><Link key={m.id} className="rising-card" href={detail(m.id)}><span className="rising-index">0{i+1}</span><div><strong>{m.title}</strong><small>{m.genre} · {compact(m.audience)}명</small></div><Change value={m.audienceChange}/><ArrowUpRight size={16}/></Link>)}{!rising.length&&<p>해당 기간에 관객이 증가한 영화가 없습니다.</p>}</div></section></div><footer className="page-footer"><span><span className="footer-mark">⌁</span>CINEPULSE</span><span>데이터 출처: {data.source==='mock'?'데모 시나리오':'영화진흥위원회 KOBIS'} · 예측은 참고용입니다.</span><span>© 2026 CINEPULSE</span></footer></main></Shell>;
}
