'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Sparkles,Info,Check,Users,Ticket,Target,Layers} from 'lucide-react';
import {CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis,Legend,Brush} from 'recharts';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Skeleton} from '@/components/ui/skeleton';
import {Shell} from './shell';
import {ForecastChart} from './chart';
import {Change} from './dashboard';
import {DEMO_DATE} from '@/lib/cinema/mock';
import {compact,forecast} from '@/lib/cinema/forecast';
import type {BoxOffice,Horizon,Metric} from '@/lib/cinema/types';
export function MovieDetail({id,source,date=DEMO_DATE}:{id:string;source:'mock'|'kobis';date?:string}){
 const [data,setData]=useState<BoxOffice|null>(null),[error,setError]=useState(''),[horizon,setHorizon]=useState<Horizon>(7),[metric,setMetric]=useState<Metric>('audience'),[compare,setCompare]=useState<string[]>([]);
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');fetch(`/api/boxoffice?source=${source}&date=${date}&history=true`,{signal:controller.signal}).then(async r=>{const d=await r.json() as BoxOffice & {error?:string};if(!r.ok)throw new Error(d.error);return d}).then((d:BoxOffice)=>{setData(d);setCompare([id,...d.movies.filter(m=>m.id!==id).slice(0,2).map(m=>m.id)])}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[id,source,date]);
 const movie=data?.movies.find(m=>m.id===id),result=useMemo(()=>movie?forecast(movie,horizon,metric):null,[movie,horizon,metric]),audience=movie?forecast(movie,horizon,'audience'):null,revenue=movie?forecast(movie,horizon,'revenue'):null;
 const compareMovies=data?.movies.filter(m=>compare.includes(m.id))||[];
 const comparison=useMemo(()=>{const dates=new Set<string>();for(const m of compareMovies){for(const d of forecast(m,horizon,metric)?.points||[])dates.add(d.date)}return [...dates].sort().map(date=>{const row:Record<string,string|number>={date};for(const m of compareMovies){const p=forecast(m,horizon,metric)?.points.find(p=>p.date===date);if(p)row[m.id]=p.actual??p.prediction??0}return row})},[compareMovies,horizon,metric]);
 return <Shell><main className="dashboard detail-page page-enter"><Link className="back-link" href="/"><ArrowLeft size={16}/>대시보드로 돌아가기</Link>{error?<div className="empty-state" role="alert"><h2>실적을 불러오지 못했습니다.</h2><p>{error}</p><Button variant="outline" asChild><Link href="/">대시보드로 이동</Link></Button></div>:!data?<div aria-label="영화 분석 불러오는 중"><Skeleton className="h-36 w-full mb-6"/><Skeleton className="h-96 w-full"/></div>:!movie?<div className="empty-state"><h1>이 집계일의 TOP 10에서 찾을 수 없는 영화입니다.</h1><p>대시보드에서 영화와 조회 날짜를 다시 선택하세요.</p></div>:<>
 <section className="detail-hero"><div className="detail-monogram" style={{'--movie-color':movie.color} as React.CSSProperties}>{movie.english.slice(0,1)}<span>NO. {String(movie.rank).padStart(2,'0')}</span></div><div className="detail-title"><div className="eyebrow">{movie.english}</div><h1>{movie.title}</h1><div className="detail-tags"><span>{movie.genre}</span><span>{movie.released} 개봉</span><span>박스오피스 {movie.rank}위</span></div><p>{data.note}</p></div><div className="detail-daily"><span>일간 관객수</span><strong>{compact(movie.audience)}<small>명</small></strong><Change value={movie.audienceChange}/></div></section>
 <div className="detail-section-title"><div><div className="section-overline"><Sparkles size={14}/> AI FORECAST · DEMO</div><h2>가능성을 숫자로 읽다</h2></div><Tabs value={String(horizon)} onValueChange={v=>setHorizon(Number(v) as Horizon)}><TabsList>{[7,14,30].map(n=><TabsTrigger key={n} value={String(n)}>{n}일 예측</TabsTrigger>)}</TabsList></Tabs></div>
 <section className="kpi-grid detail-kpis">{[{label:`${horizon}일 추가 관객 예측`,value:audience?compact(audience.total):'—',unit:'명',foot:audience?`${compact(audience.lower)} ~ ${compact(audience.upper)}명`:'최근 실적 부족',icon:Users},{label:`${horizon}일 추가 매출 예측`,value:revenue?compact(revenue.total):'—',unit:'원',foot:revenue?`${compact(revenue.lower)} ~ ${compact(revenue.upper)}원`:'최근 실적 부족',icon:Ticket},{label:'흥행확률 · 데모',value:audience?String(audience.probability):'—',unit:'%',foot:`기간 내 추가 100만 관객 기준`,icon:Target},{label:'누적 관객수',value:compact(movie.cumulative),unit:'명',foot:`${data.date}까지 집계`,icon:Layers}].map((k,i)=><article className={`kpi ${i===2?'kpi-purple':''}`} key={k.label}><div className="kpi-label">{k.label}<k.icon size={16}/></div><div className="kpi-value">{k.value}<span>{k.unit}</span></div><div className="kpi-foot">{k.foot}</div></article>)}</section>
 <article className="panel detail-chart"><div className="panel-heading"><div><h2>실제 실적과 AI 예측</h2><p>최근 14일의 일별 실적 · 앞으로 {horizon}일의 시뮬레이션</p></div><Tabs value={metric} onValueChange={v=>setMetric(v as Metric)}><TabsList><TabsTrigger value="audience">관객수</TabsTrigger><TabsTrigger value="revenue">매출</TabsTrigger></TabsList></Tabs></div><div className="chart-legend detail-legend"><span><i className="actual-dot"/>{source==='mock'?'샘플 실적':'KOBIS 실적'}</span><span><i/>예측</span><span><i/>신뢰구간 (시뮬레이션)</span></div>{result?<ForecastChart points={result.points} metric={metric} cutoff={movie.history.at(-1)!.date}/>:<div className="empty-state">연속 7일 이상의 실적이 있어야 예측을 생성합니다. TOP 10 밖의 실적은 0명으로 간주하지 않습니다.</div>}<div className="model-explanation"><Info size={16}/><p>최근 7일 평균과 추세, 요일 효과를 사용하는 데모 모델입니다. 음영 구간과 흥행확률은 검증·보정되지 않은 시뮬레이션이며, 학습된 AI 모델의 결과가 아닙니다. 흥행확률의 기준은 선택한 예측 기간 내 <strong>추가 관객 100만 명</strong>입니다.</p></div></article>
 <section className="comparison-section"><div className="section-heading"><div><h2>같은 시장, 다른 흐름</h2><p>경쟁작을 최대 3편까지 선택해 실적과 예측을 비교하세요.</p></div><span className="top10">{compare.length} / 3 SELECTED</span></div><div className="compare-picker">{data.movies.map(m=><Button key={m.id} variant="outline" aria-pressed={compare.includes(m.id)} disabled={m.id===id||(!compare.includes(m.id)&&compare.length>=3)} className={compare.includes(m.id)?'selected':''} onClick={()=>setCompare(v=>v.includes(m.id)?v.filter(x=>x!==m.id):[...v,m.id])}>{compare.includes(m.id)&&<Check size={13}/>} {m.title}</Button>)}</div><article className="panel compare-panel"><div className="comparison-chart" role="img" aria-label="선택한 경쟁작 실적과 예측 비교 그래프"><ResponsiveContainer width="100%" height="100%"><LineChart data={comparison} margin={{top:20,right:25,left:5,bottom:10}}><CartesianGrid stroke="#2b2433" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} tick={{fill:'#a48aaf',fontSize:12}} minTickGap={35} tickLine={false} axisLine={false}/><YAxis tickFormatter={compact} tick={{fill:'#a48aaf',fontSize:12}} width={55} tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:'#201928',border:'1px solid #4a3456',borderRadius:9}} formatter={v=>compact(Number(v))+(metric==='audience'?'명':'원')}/><Legend wrapperStyle={{fontSize:12,paddingTop:10}}/>{compareMovies.map((m,i)=><Line key={m.id} dataKey={m.id} name={m.title} stroke={['#b699f9','#71cdb5','#d7ac72'][i]} strokeWidth={2} dot={false}/>)}<Brush dataKey="date" height={18} stroke="#5b416c" fill="#21192c" tickFormatter={v=>v.slice(5)} travellerWidth={7}/></LineChart></ResponsiveContainer></div><div className="chart-bottom"><span>{data.date} 이후 구간은 예측값입니다. 아래 범위 조절기로 확대할 수 있습니다.</span></div></article><div className="compare-stats">{compareMovies.map((m,i)=>{const f=forecast(m,horizon,metric);return <div key={m.id} className="panel compare-stat"><span style={{color:['#b699f9','#71cdb5','#d7ac72'][i]}}>{m.title}</span><strong>{f?compact(f.total):'실적 부족'}<small>{metric==='audience'?'명':'원'}</small></strong><span>향후 {horizon}일 합계</span></div>})}</div></section><div className="detail-end"><span>실적 기준 {data.date} · 예매율 {movie.reservation!=null?`${movie.reservation}% (샘플)`:'미제공'}</span><Link href="/">다른 영화 살펴보기 <ArrowUpRight size={15}/></Link></div>
 </>}</main></Shell>;
}
