'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Activity,LayoutGrid,ChartNoAxesCombined,Flame,ArrowUpRight} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarProvider,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname();
 return <SidebarProvider style={{'--sidebar-width':'224px'} as React.CSSProperties}><Sidebar className="cine-sidebar"><SidebarHeader><Link href="/" className="brand"><span className="brand-icon"><Activity size={23}/></span>CINEPULSE<span className="brand-dot">®</span></Link><div className="workspace"><span className="workspace-logo">C</span><span>Cinema workspace<small>흥행 인텔리전스</small></span><span className="workspace-plan">PRO</span></div></SidebarHeader><SidebarContent><div className="nav-label">WORKSPACE</div><SidebarMenu>{[{href:'/',label:'대시보드',icon:LayoutGrid},{href:'/#boxoffice',label:'박스오피스',icon:ChartNoAxesCombined},{href:'/#rising',label:'급상승 영화',icon:Flame}].map(n=><SidebarMenuItem key={n.href}><SidebarMenuButton asChild isActive={n.href==='/'&&path==='/'}><Link href={n.href}><n.icon size={17}/><span>{n.label}</span>{n.href==='/'&&<span className="nav-pill">10</span>}</Link></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><span className="tiny-spark">✦</span><strong>다음 흥행을 읽다.</strong><p>실적의 흐름에서<br/>영화의 가능성까지.</p><Link href="/movies/demo-1">예측 살펴보기 <ArrowUpRight size={14}/></Link></div></SidebarContent><SidebarFooter><div className="source-caption"><span/>CINEMA INTELLIGENCE</div><div className="account"><span className="avatar">C</span><span>Cinema analyst<small>Personal workspace</small></span></div></SidebarFooter></Sidebar><div className="app-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger aria-label="메뉴 열기" className="mobile-menu"/><span>워크스페이스</span><span>/</span><strong>{path.startsWith('/movies')?'영화 상세':'대시보드'}</strong></div><span className="topbar-right">KOREAN BOX OFFICE <span className="timezone">KST</span></span></header>{children}</div></SidebarProvider>;
}
